FROM golang:alpine
MAINTAINER Yotam Cohen <yotam.cohen@endocode.com>

COPY . /src/gitlab-mr-services
WORKDIR /src/gitlab-mr-services
RUN apk add --no-cache git util-linux \ 
    && go get -v -d
RUN go build
RUN ln -s /src/gitlab-mr-services/gitlab-mr-services /go/bin/gitlab-mr-services
